apiVersion: apps/v1
kind: Deployment
metadata:
    name: signal-engine
    labels:
      app: signal-engine
spec:
    replicas: 1
    selector:
      matchLabels:
        app: signal-engine
    template:
      metadata:
        labels:
          app: signal-engine
      spec:
        containers:
        - name: signal-engine
          image: kingaiva/signal-engine:dev
          env:
            - name: INTERVAL
              valueFrom:
                secretKeyRef:
                  name: strategy-config
                  key: interval
            - name: PERIOD
              valueFrom:
                secretKeyRef:
                  name: strategy-config
                  key: period
            - name: WINDOW
              valueFrom:
                secretKeyRef:
                  name: strategy-config
                  key: window
            - name: NUM_STD
              valueFrom:
                secretKeyRef:
                  name: strategy-config
                  key: num_std
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: se-port
          env:
          - name: PORT
            value: "8000"