---
name: deploy-stockflow
on:
  workflow_run:
    workflows:
      - build-image-and-push
    types:
      - completed
jobs:
 build:
   name: deploy-stockflow
   runs-on: self-hosted
   steps:
   - name: Checkout
     uses: actions/checkout@v2
 
   - name: deploy-microservice
     env:
       SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
     run: |
       bash deploy_project.sh
